on: [push]

jobs:
  ostorlab_test:
    runs-on: ubuntu-latest
    name: Ostorlab Android Scan

    steps:
      - uses: actions/checkout@v4

      - name: Download APK
        run: |
          wget https://github.com/dineshshetty/Android-InsecureBankv2/raw/master/InsecureBankv2.apk
          mv InsecureBankv2.apk ostorlab.apk

      - name: Verify APK
        run: ls -lh ostorlab.apk

      - name: Launch Ostorlab scan
        uses: Ostorlab/ostorlab_actions@v1.1.0
        with:
          scan_profile: fast_scan
          asset_type: android-apk
          target: ostorlab.apk
          scan_title: title_scan_ci
          ostorlab_api_key: ${{ secrets.ostorlab_api_key }}
          break_on_risk_rating: HIGH
